### ISSUE TITLE
Extra Map Options

### ISSUE THREAD

**Issue by techfoxis** [Serenity-MC/SerenityMapManager#1]
Implement extra options for maps. They should interface with the following config:
---
*config.yml*
```
maps:
    example_map:
        autoload: true
        clearItems: true
        gamemode: 2
        resetInterval: 25
        persistent: false
        resourcepackURL: www.google.com
```
